"""initial_schema

Revision ID: 61ae879a1c95
Revises:
Create Date: 2026-05-08 03:48:36.566607

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "61ae879a1c95"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bodegas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=150), nullable=False),
        sa.Column("ciudad", sa.String(length=100), nullable=False),
        sa.Column("direccion", sa.String(length=255), nullable=False),
        sa.Column("capacidad", sa.Integer(), nullable=False),
        sa.Column("tipo", sa.Enum("NACIONAL", "INTERNACIONAL", name="tipobodega"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "clientes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=150), nullable=False),
        sa.Column("nit", sa.String(length=20), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("telefono", sa.String(length=20), nullable=False),
        sa.Column("direccion", sa.String(length=255), nullable=False),
        sa.Column("ciudad", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_clientes_nit"), "clientes", ["nit"], unique=True)
    op.create_table(
        "productos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=150), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("categoria", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "puertos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=150), nullable=False),
        sa.Column("ciudad", sa.String(length=100), nullable=False),
        sa.Column("pais", sa.String(length=100), nullable=False),
        sa.Column("codigo", sa.String(length=10), nullable=False),
        sa.Column("tipo", sa.Enum("NACIONAL", "INTERNACIONAL", name="tipopuerto"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_puertos_codigo"), "puertos", ["codigo"], unique=True)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("nombre", sa.String(length=100), nullable=False),
        sa.Column("rol", sa.String(length=50), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "envios_maritimos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("numero_guia", sa.String(length=10), nullable=False),
        sa.Column("cliente_id", sa.Integer(), nullable=False),
        sa.Column("producto_id", sa.Integer(), nullable=False),
        sa.Column("puerto_id", sa.Integer(), nullable=False),
        sa.Column("cantidad", sa.Integer(), nullable=False),
        sa.Column("fecha_registro", sa.Date(), nullable=False),
        sa.Column("fecha_entrega", sa.Date(), nullable=False),
        sa.Column("precio_envio", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("descuento_pct", sa.Numeric(precision=4, scale=2), nullable=False),
        sa.Column("precio_final", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("numero_flota", sa.String(length=8), nullable=False),
        sa.Column(
            "estado",
            sa.Enum("PENDIENTE", "EN_TRANSITO", "ENTREGADO", "CANCELADO", name="estadoenvio"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cliente_id"],
            ["clientes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["producto_id"],
            ["productos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["puerto_id"],
            ["puertos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_envios_maritimos_numero_guia"), "envios_maritimos", ["numero_guia"], unique=True
    )
    op.create_table(
        "envios_terrestres",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("numero_guia", sa.String(length=10), nullable=False),
        sa.Column("cliente_id", sa.Integer(), nullable=False),
        sa.Column("producto_id", sa.Integer(), nullable=False),
        sa.Column("bodega_id", sa.Integer(), nullable=False),
        sa.Column("cantidad", sa.Integer(), nullable=False),
        sa.Column("fecha_registro", sa.Date(), nullable=False),
        sa.Column("fecha_entrega", sa.Date(), nullable=False),
        sa.Column("precio_envio", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("descuento_pct", sa.Numeric(precision=4, scale=2), nullable=False),
        sa.Column("precio_final", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("placa", sa.String(length=6), nullable=False),
        sa.Column(
            "estado",
            sa.Enum("PENDIENTE", "EN_TRANSITO", "ENTREGADO", "CANCELADO", name="estadoenvio"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bodega_id"],
            ["bodegas.id"],
        ),
        sa.ForeignKeyConstraint(
            ["cliente_id"],
            ["clientes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["producto_id"],
            ["productos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_envios_terrestres_numero_guia"), "envios_terrestres", ["numero_guia"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_envios_terrestres_numero_guia"), table_name="envios_terrestres")
    op.drop_table("envios_terrestres")
    op.drop_index(op.f("ix_envios_maritimos_numero_guia"), table_name="envios_maritimos")
    op.drop_table("envios_maritimos")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_puertos_codigo"), table_name="puertos")
    op.drop_table("puertos")
    op.drop_table("productos")
    op.drop_index(op.f("ix_clientes_nit"), table_name="clientes")
    op.drop_table("clientes")
    op.drop_table("bodegas")
    # ### end Alembic commands ###
